name: Docker CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build Docker image
      uses: docker build -t app.py:${{ github.sha }} .

    - name: List Docker images
      run: docker images

    - name: Test Docker image runs
      run: |
          docker run -d --name test-container app.py:${{ github.sha }}
          sleep 5
          docker ps
          docker logs test-container
          docker stop text-container
          
